font:
  normal:
    family: Source Code Pro
  size: 7.0
key_bindings:
  - { key: F11, action: ToggleFullscreen }
dynamic_padding: true
#background_opacity: 0.9

# https://github.com/eendroroy/alacritty-theme
# atom_one_light:
#colors: {primary: {background: '0xf8f8f8', foreground: '0x2a2b33'}, normal: {black: '0x000000', red: '0xde3d35', green: '0x3e953a', yellow: '0xd2b67b', blue: '0x2f5af3', magenta: '0xa00095', cyan: '0x3e953a', white: '0xbbbbbb'}, bright: {black: '0x000000', red: '0xde3d35', green: '0x3e953a', yellow: '0xd2b67b', blue: '0x2f5af3', magenta: '0xa00095', cyan: '0x3e953a', white: '0xffffff'}}
# dark_pastels:
colors: {primary: {background: '0x1C1C1C', foreground: '0xDCDCCC'}, normal: {black: '0x3F3F3F', red: '0x705050', green: '0x60B48A', yellow: '0xDFAF8F', blue: '0x9AB8D7', magenta: '0xDC8CC3', cyan: '0x8CD0D3', white: '0xDCDCCC'}, bright: {black: '0x709080', red: '0xDCA3A3', green: '0x72D5A3', yellow: '0xF0DFAF', blue: '0x94BFF3', magenta: '0xEC93D3', cyan: '0x93E0E3', white: '0xFFFFFF'}}
#VIM_DARKMODE=1 # This line is read from init.vim to select color theme
