#!/usr/bin/env bash

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

install() {
    cp "$REPO_DIR/$1" "$HOME/$1"
}

install .bashrc
install .vimrc
install .gitignore_global
install .gitconfig
install .tmux.conf

vscode_loc=''
if       [[ -d '/c/Users/jaburns/AppData/Roaming/Code/User' ]]; then
    vscode_loc='/c/Users/jaburns/AppData/Roaming/Code/User'
elif     [[ -d '/Users/jaburns/Library/Application Support/Code/User' ]]; then
    vscode_loc='/Users/jaburns/Library/Application Support/Code/User'
elif     [[ -d '/home/jaburns/.config/Code/User' ]]; then
    vscode_loc='/home/jaburns/.config/Code/User'
else
    echo 'Couldnt find VSCode settings.json'
fi

if [[ ! -z "$vscode_loc" ]]; then
    cp "$REPO_DIR/vscode_settings.json" "$vscode_loc/settings.json"
    cp "$REPO_DIR/vscode_keybindings.json" "$vscode_loc/keybindings.json"
fi

if [[ -d '/home/jaburns/.config/xfce4' ]]; then
    cp xfce/xfce4-keyboard-shortcuts.xml /home/jaburns/.config/xfce4/xfconf/xfce-perchannel-xml
fi
