#!/bin/bash

# Get the script's running folder.
repo_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

files_windows=$( cat <<EOF
.minttyrc
EOF
)

files_basic=$( cat <<EOF
.bashrc
.tmux.conf
.vimrc
EOF
)

files_xmonad=$( cat <<EOF
.conkyrc
.conky.lua
.xmonad/set-machine.sh
.xmonad/lib/CustomLog.hs
.xmonad/lib/XMonadConfig.hs
EOF
)

# TODO Link .xmonad as a folder, and link .vim in *nix

do_files () {
    for x in $*; do
        [ -a "$HOME/$x" ] && rm "$HOME/$x"
        mkdir -p "$(dirname "$HOME/$x")"
        ln "$repo_dir/$x" "$HOME/$x"
        echo "$repo_dir/$x" '==>' "$HOME/$x"
    done
}

echo ""
echo "Linking $1 config files..."
eval "do_files \$files_$1"
echo "Done!"
echo ""

if [ "$1" == 'windows' ]; then
    echo "Linking windows vim files..."

    rm -f "/cygdrive/c/Users/$(whoami)/_vimrc"
    rm -rf "/cygdrive/c/Users/$(whoami)/vimfiles"

    ln "$repo_dir/.vimrc" "/cygdrive/c/Users/$(whoami)/_vimrc"
    echo "$repo_dir/.vimrc" '==>' "/cygdrive/c/Users/$(whoami)/_vimrc"

    echo "mklink /j \"c:\\Users\\$(whoami)\\vimfiles\" \"C:\\cygwin\\home\\jaburns\\dotfiles\\.vim\"" | cmd

    echo "Done!"
    echo ""
fi

