#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
REPO_DIR="$( pwd )"

MODE="$1"
shift

if [[ "$MODE" != 'pull' ]] && [[ "$MODE" != 'install' ]]; then
    echo 'Usage: ./manage [install | pull] [light]?'
    exit 1
fi

copy_file() {
    if [[ "$MODE" == 'install' ]]; then
        cp "$1" "$2"
    else
        cp "$2" "$1"
    fi
}

copy_home() {
    copy_file "$REPO_DIR/$1" "$HOME/$1"
}

[[ "$MODE" == 'install' ]] && mkdir -p "$HOME/.config/nvim/colors"

copy_home .bashrc
copy_home .gitignore_global
copy_home .gitconfig
copy_home .tmux.conf
copy_home .alacritty.yml
copy_file "$REPO_DIR/redshift.conf" "$HOME/.config/redshift.conf"
copy_file "$REPO_DIR/init.vim" "$HOME/.config/nvim/init.vim"
copy_file "$REPO_DIR/coc-settings.json" "$HOME/.config/nvim/coc-settings.json"
copy_file "$REPO_DIR/colors/corvine.vim" "$HOME/.config/nvim/colors/corvine.vim"
copy_file "$REPO_DIR/colors/envy.vim" "$HOME/.config/nvim/colors/envy.vim"

[[ -d "$HOME/.config/xfce4" ]] && \
    copy_file 'xfce4-keyboard-shortcuts.xml' \
        "$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

if [[ "$MODE" == 'install' ]]; then
    if [[ ! -f '/usr/share/xfce4/terminal/colorschemes/xfce4-terminal-dark-theme.theme' ]]; then
        sudo cp xfce4-terminal-dark-theme.theme /usr/share/xfce4/terminal/colorschemes/
        sudo cp xfce4-terminal-light-theme.theme /usr/share/xfce4/terminal/colorschemes/
    fi
fi
