#!/usr/bin/env bash

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pull() {
    cp "$HOME/$1" "$REPO_DIR/$1"
}

pull .bashrc
pull .vimrc
pull .gitignore_global

if [[ -d '/mnt/c/Users/jaburns/AppData/Roaming/Code/User' ]]; then
    cp '/mnt/c/Users/jaburns/AppData/Roaming/Code/User/settings.json' "$REPO_DIR/vscode_settings.json"
fi

if [[ -d '/mnt/c/Users/jaburns' ]]; then
    cp ~/.gitconfig "$REPO_DIR/windows.gitconfig"
    cp ~/.dircolors "$REPO_DIR/windows.dircolors"
fi

if [[ "$OSTYPE" == *darwin* ]]; then
    pull .vrapperrc
    pull .slate
    cp '/Users/jaburns/Library/Application Support/Code/User/settings.json' "$REPO_DIR/vscode_settings.json"
    cp ~/.gitconfig "$REPO_DIR/osx.gitconfig"
fi
