#!/usr/bin/env bash

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pull() {
    cp "$HOME/$1" "$REPO_DIR/$1"
}

pull .bashrc
pull .vimrc
pull .gitignore_global
pull .gitconfig
pull .tmux.conf

vscode_loc=''
if       [[ -d '/c/Users/jaburns/AppData/Roaming/Code/User' ]]; then
    vscode_loc='/c/Users/jaburns/AppData/Roaming/Code/User'
elif     [[ -d '/Users/jaburns/Library/Application Support/Code/User' ]]; then
    vscode_loc='/Users/jaburns/Library/Application Support/Code/User'
elif     [[ -d '/home/jaburns/.config/Code/User' ]]; then
    vscode_loc='/home/jaburns/.config/Code/User'
else
    echo 'Couldnt find VSCode settings.json'
fi

if [[ ! -z "$vscode_loc" ]]; then
    cp "$vscode_loc/settings.json" "$REPO_DIR/vscode_settings.json"
    cp "$vscode_loc/keybindings.json" "$REPO_DIR/vscode_keybindings.json"
fi
