#!/usr/bin/env bash

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pull() {
    cp "$HOME/$1" "$REPO_DIR/$1"
}

pull .bashrc
pull .vimrc
pull .gitignore_global
pull .gitconfig
pull .tmux.conf

vscode_loc=''
if [[ -d '/c/Users/jaburns/AppData/Roaming/Code/User' ]]; then
    vscode_loc='/c/Users/jaburns/AppData/Roaming/Code/User/settings.json'
elif [[ -d '/Users/jaburns/Library/Application Support/Code/User' ]]
    vscode_loc='/Users/jaburns/Library/Application Support/Code/User/settings.json'
elif [[ -d '/home/jaburns/.config/Code/User' ]]
    vscode_loc='/home/jaburns/.config/Code/User/settings.json'
else
    echo 'Couldnt find VSCode settings.json'
fi

if [[ ! -z "$vscode_loc" ]]; then
    cp "$vscode_loc" "$REPO_DIR/vscode_settings.json" 
fi
