#!/usr/bin/env sh

VS_MERGE='/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/vsDiffMerge.exe'

get_filename() {
    echo "$1" | sed 's:.*/::'
}

resolve_path() {
    cd "$(dirname "$1")"
    local base_path="$(pwd -P | sed 's:/mnt/::;s_/_:/_;s:/:\\:g')"
    echo "$base_path\\$(get_filename "$1")"
}

do_diff() {
    tmpLocal="$(get_filename $1)"
    remote="$(resolve_path "$2")"
    cp "$1" "/mnt/c/Windows/Temp/$tmpLocal"
    "$VS_MERGE" "C:\\Windows\\Temp\\$tmpLocal" "$remote" Source Target //t
}

do_merge() {
    echo "$@"
    # TODO implement merge tool
    # cmd = $VS_MERGE $LOCAL $REMOTE $BASE $MERGED //m
}

case "$1" in
    diff)  do_diff  "$2" "$3" ;;
    merge) do_merge "$2" "$3" "$4" "$5" ;;
esac




