#!/usr/bin/env bash

>/tmp/win_move.js echo '
const TASK_BAR_HEIGHT = 24;
const LAYOUTS = [
    // x, y, w, h
    [ 0.25, 0.0, 0.5, 1.0 ]
];

const { win, monitors } = JSON.parse(process.argv[2]);

const layout = LAYOUTS[parseInt(process.argv[3])];

const woff = 2 * win[2];
const hoff = win[2] + win[3];

const ox = win[0] - win[2];
const oy = win[1] - win[3];
const ow = win[4] + woff;
const oh = win[5] + hoff;

const cx = ox + ow / 2;
const cy = oy + oh / 2;

let monitorIndex = 0;

for (let i = 0; i < monitors.length; ++i) {
    const [ mw, mh, mx, my ] = monitors[i];
    if (cx >= mx && cx <= mx + mw && cy >= my && cy <= my + mh) {
        monitorIndex = i;
        break;
    }
}

const [ mw, mh0, mx, my ] = monitors[monitorIndex];
const mh = mh0 - TASK_BAR_HEIGHT;

const nx = mx + layout[0] * mw;
const ny = my + layout[1] * mh;
const nw = layout[2] * mw;
const nh = layout[3] * mh;

console.log(`${nx},${ny},${nw - woff},${nh - hoff}`);
'

make_array_from_lines() {
    xargs echo \
        | sed 's/^/\[/;s/ /,/g;s/$/\]/'
}

get_win_id() {
    xprop -root _NET_ACTIVE_WINDOW \
        | sed 's/.* # //g;s/, .*//g'
}

get_win_info() {
    xwininfo -id "$1" \
        | grep -E "upper-left|Width:|Height:" \
        | cut -d: -f2 \
        | make_array_from_lines 
}

get_monitor_info() {
    xrandr \
        | grep ' connected' \
        | grep -v 'connected (' \
        | cut -d\  -f3 \
        | sed 's/[+x]/,/g;s/^/\[/;s/$/\]/' \
        | make_array_from_lines 
}

get_json() {
    local win="$(get_win_info $win_id)"
    local monitors="$(get_monitor_info)"

    echo "{\"win\":$win,\"monitors\":$monitors}"
}

main() {
    local win_id="$(get_win_id)"
    local new_xywh="$(node /tmp/win_move.js "$(get_json)" "$1")"

    wmctrl -i -r "$win_id" -e "0,$new_xywh"
}

main "$1"
