#!/usr/bin/env bash

# Fixes the window buttons showing for the wrong display in xfce panel.
# https://bugzilla.xfce.org/show_bug.cgi?id=10725#c30

plugins=$(xfconf-query -c xfce4-panel -lv | grep tasklist | cut -f1 -d' ')
for plugin in $plugins; do
    xfconf-query -c xfce4-panel -p $plugin/include-all-monitors -s true
    xfconf-query -c xfce4-panel -p $plugin/include-all-monitors -s false
done
echo Configured these taskbar plugins: $plugins
