#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo 'usage: ./gfm-render {markdown file} {optional: repository context}'
    exit
fi

css='https://gist.githubusercontent.com/andyferra/2554919/raw/2e66cabdafe1c9a7f354aa2ebf5bc38265e638e5/github.css'

data="$(
    cat "$1" \
      | sed 's/"/\\"/g' \
      | sed ':a;N;$!ba;s/\n/\\n/g' \
)"

if [[ -z "$2" ]]; then
    context=''
else
    context=",\"context\":\"$2\""
fi

echo '<!DOCTYPE html>'
echo '<html><head><style>'
curl -s $css
echo '</style></head><body>'
curl -s --data "{\"text\":\"$data\",\"mode\":\"gfm\"$context}" 'https://api.github.com/markdown'
echo '</body></html>'

