#!/bin/bash

# Thanks to Sirupsen for this tool!
#   http://sirupsen.com/a-simple-imgur-bash-screenshot-utility/

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" \
      https://imgur.com/api/upload.xml \
    | grep -E -o "<original_image>(.)*</original_image>" \
    | grep -E -o "http://i.imgur.com/[^<]*"
}

uploadImage "$1" | xclip -selection c
rm "$1"
notify-send "Image Uploaded"

