#!/usr/bin/env bash

extramaus &

vlc \
    --no-video-deco \
    --no-embedded-video \
    --screen-fps=20 \
    --screen-top=0 \
    --screen-left=1920 \
    --screen-width=2560 \
    --screen-height=1440 \
    screen:// &
