#!/bin/bash

# Pull the svn log, and count the commits on each date.
commits=`svn log|grep '|'|cut -d\  -f5|uniq -c|tr -s ' '`

# Defines a function to filter the list of commits per date.
fc(){ echo "$commits"|$1|cut -d\  -f$2;}

# Get the first and last dates in the log.
first=`fc 'tail -1' 3`
last=`fc 'head -1' 3`

# Define the date command and format parameter.
dt='date +%Y-%m-%d -d'
now=`$dt "$first - 1 day"`
end=`$dt "$last"`

# Loop from first to last date in log.
while [[ "$now" < "$end" ]] ; do
  now=`$dt "$now + 1 day"`
  # Look up the number of commits for this date, and draw that many ticks.
  ticks=`printf "%$(fc "grep $now" 2)s" | tr " " "O"`
  echo "$now $ticks"
done

